### ISSUE TITLE
Is it normal for it to be this slow?

### ISSUE THREAD

**Issue by acer51-doctom** [Mewtality/TCPGecko-MK8-Mod-Menu#1]
It's really slow when i wanna change the menus or switch to another mod

**Comment by Mewtality** [comment]
No it's not normal, project's been updated just now, let me know if the issue persists.
Note that due to limitations the mod menu can only read 1 input at a time.

**Comment by acer51-doctom** [comment]
In reply to @Mewtality 

HELLO SO I JUST SAW THE MESSAGE AND UH...
Yeah, I'll test it out again :3
